spring.application.name=Sistema de Quejas Bancario - CU01 y CU02
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
adjuntos.directorio=uploads
# CU01 FA03: cierre de sesion automatico por inactividad (configurable, valor en minutos).
server.servlet.session.timeout=15m

spring.datasource.url=jdbc:postgresql://ep-sweet-violet-ayas8j66-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=local